#Title-Assignment 1-Marzan Wahab

library(readr)
Cereals <- read_csv("Cereals.csv")
# Dataset provided from course module
View(Cereals) 

# Print out descriptive stats for categorical variables
table(Cereals$mfr)

table(Cereals$type)


# print out descriptive statistics for quantitative var (sugars,fats)
print("summary of sugars and fats")
summary(Cereals[,c("sugars","fat")])

#table Output
#  sugars            fat       
# Min.   : 0.000   Min.   :0.000  
#1st Qu.: 3.000   1st Qu.:0.000  
#Median : 7.000   Median :1.000  
#Mean   : 7.026   Mean   :1.013  
#3rd Qu.:11.000   3rd Qu.:2.000  
#Max.   :15.000   Max.   :5.000  
#NA's   :1                 
 
#summareize quantatitive var by group category(mfr)-installed dplyr
 
Cereals %>% 
  group_by(mfr) %>% 
  summarise(
   count=n(),
    mean_sugars=mean(sugars,na.rm=TRUE),
    median_sugars=median(sugars,na.rm=TRUE),
    sd_sugars=sd(sugars,na.rm=TRUE),
    mean_fat=mean(fat, na.rm=TRUE),
    median_fat=median(fat,na.rm=TRUE),
    sd_fat=sd(fat,na.rm=TRUE),
    )
# test  
    